services:
  dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    container_name: idea-dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      SESSION_SECRET: ${SESSION_SECRET}
    networks:
      - network
    volumes:
      - .:/work/app
    depends_on:
      - redis

  redis:
    container_name: idea-redis
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_MAX_MEMORY: ${REDIS_MAX_MEMORY}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--maxmemory", "${REDIS_MAX_MEMORY}", "--maxmemory-policy", "allkeys-lru"]
    networks:
      - network

volumes:
  redis-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./redis

networks:
  network:
    driver: bridge
