FROM node:18

WORKDIR /work/app

COPY package*.json ./

COPY .env ./.env

RUN npm install

COPY ./src /work/app/src

EXPOSE 3000

RUN npm install -g nodemon

RUN npm install -g sequelize-cli

CMD ["npm", "run", "dev"]
